# Generated by Django 2.2.7 on 2019-11-08 02:41

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('venue_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=50)),
                ('coordinates', jsonfield.fields.JSONField()),
                ('time_spent', jsonfield.fields.JSONField()),
                ('popular_times', jsonfield.fields.JSONField()),
            ],
        ),
    ]
