# Generated by Django 2.2.7 on 2019-11-08 14:45

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='music_type',
            field=models.CharField(default='ALL', max_length=50),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='radius',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='current_popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='rating_n',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='venue_type',
            field=models.CharField(default='ALL', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='coordinates',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='venue',
            name='popular_times',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='venue',
            name='time_spent',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
