# Generated by Django 2.2.7 on 2019-11-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191108_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='rating_n',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='types',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='radius',
            field=models.IntegerField(default=5000),
        ),
    ]
