# Generated by Django 2.2.7 on 2019-11-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191108_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='place_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
