# Generated by Django 2.2.7 on 2019-11-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_venue_place_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='popular_times',
            new_name='populartimes',
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='venue',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='rating_n',
            field=models.IntegerField(default=0),
        ),
    ]
