# Generated by Django 2.2.7 on 2019-11-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191108_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='time_spent',
            new_name='time_wait',
        ),
    ]
