# Generated by Django 2.2.7 on 2019-11-08 18:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191108_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='time_wait',
            new_name='wait_time',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='wait_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='venue',
            name='coordinates',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
